openapi: '3.0.3'
info:
  title: i3M-Wallet Cloud-Vault API
  version: '1.0'
paths:
  /api/API_VERSION/publicJwk:
    get:
      description: >
        Get the current wallet cloud-vault's public key as a JWK
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schema/jwk.yaml#/components/schemas/JwkEcPublicKey"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "./schema/api-error.yaml#/components/schemas/ApiError"
    
