openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'

paths:
  /_IGNORE_PATH:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    RegistrationData:
      type: string
      title: RegistrationData
      description: |
        A compact JWE encrypted with this server's public key with the following payload:

        ```json
        {
          did: string
          username: string
          authkey: string
        }
        ```
        
        - `did` is the did of the user. The required authorization forces the user to prove that is the owner of this `did`
        - `username` is a unique username proposed by the client (it should be able to memorize it)
        - `authkey` is a secret securely derived from the user's password, so can be recovered if the user remembers the password. `authkey` will work as a standard password server side.
      pattern: ^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]*){4}$
    
    RegistrationResponse:
      type: object
      title: Registration Response
      description: |
        The registration response object.
      required:
        - status
        - username
      properties:
        status:
          type: string
          description: whether the proposed username has been registered or not (because another one was previously registered)
          enum:
            - created
            - already registered
        username:
          type: string
          description: |
            - `status === 'created'`: the registered username
            - `status === 'already registered'`: the username that was previously registered fot the same DID.
