openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'

paths:
  /_IGNORE_PATH:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:
    EthereumAddress:
      title: Ethereum Address in EIP-55 format (with checksum)
      type: string
      pattern: '^0x([0-9A-Fa-f]){40}$'
      example: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F'

    did: 
      title: DID
      type: string
      pattern: '^did:ethr:(\w+:)?0x[0-9a-fA-F]{40}([0-9a-fA-F]{26})?$'
      example: did:ethr:i3m:0x031bee96cfae8bad99ea0dd3d08d1a3296084f894e9ddfe1ffe141133e81ac5863

    IdentityData:
      title: Identity Data
      type: object
      properties:
        did:
          type: string
          example: did:ethr:i3m:0x03142f480f831e835822fc0cd35726844a7069d28df58fb82037f1598812e1ade8
        alias:
          type: string
          example: identity1
        provider:
          type: string
          example: did:ethr:i3m
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/EthereumAddress"
          example: ["0x8646cAcF516de1292be1D30AB68E7Ea51e9B1BE7"]
      required:
        - did
        

